In [1]:
             #ARITHMETIC OPERATION

In [4]:
import numpy as np
a=[1,2,3,4]
b=[6,4,2,1]
c=np.add(a,b)
print(c)

[7 6 5 5]


In [5]:
a=[1,2,3,4]
b=[6,4,2,1]
c=np.subtract(a,b)
print(c)

[-5 -2  1  3]


In [7]:
a=[1,2,3,4]
b=[6,4,2,1]
c=np.multiply(a,b)
print(c)

[6 8 6 4]


In [8]:
a=[1,2,3,4]
b=[6,4,2,1]
c=np.mod(a,b)
print(c)

[1 2 1 0]


In [9]:
a=[1,2,3,4]
b=[6,4,2,1]
c=np.divide(a,b)
print(c)

[0.16666667 0.5        1.5        4.        ]


In [10]:
a=[1,2,3,4]
b=[6,4,2,1]
c=np.power(a,b)
print(c)

[ 1 16  9  4]


In [12]:
a=[1,2,3,4]
b=[6,4,2,1]
c=np.reciprocal(c)
print(c)

[1 0 0 0]
