                               #Array

In [8]:
import numpy as np 
l=[1,2,3,4,5]
y= np.array(l)
print(y)
print(type(y))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [21]:
l=[]
for i in range(1,5):
    int_1 =int(input("Enter:"))
    l.append(int_1)
print(np.array(l))

Enter: 20
Enter: 30
Enter: 40
Enter: 50


[20 30 40 50]


In [24]:
# 2d array
l=[[1234],[2345]]
a=np.array(l)
print(a.ndim)


2


In [30]:
a=[[1,2,3,1],[1,2,3,1,1]]
z=np.array(a)
print(z.ndim)
# here we can see that when we are using the list it shows error while we are using list under list (& there element are not same )

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [31]:
a=[[1231],[12311]]
z=np.array(a)
print(z.ndim)
# here it doesn't show error because it is in array form 

2


In [38]:
ar2=np.array([[1234],[123]])
print(ar2)
print(ar2.ndim)

[[1234]
 [ 123]]
2


In [40]:
ar3=np.array([[[1234],[123],[123414]]])
print(ar3)
print(ar3.ndim)

[[[  1234]
  [   123]
  [123414]]]
3
