In [1]:
# creation of array 

In [2]:
import numpy as np

In [4]:
# array filled with zeros 
arr_zer= np.zeros(4)
print(arr_zer)

[0. 0. 0. 0.]


In [9]:
# for 2 d array zeros
arr_zer1 = np.zeros(((4,5,4)))
print(arr_zer1)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [10]:
# for ones it's same instead of zeros use ones 
arr_one=np.ones(2)
print(arr_one)

[1. 1.]


In [12]:
# for empty array 
arr_em=np.empty(2)
print(arr_em)

[1. 1.]


In [13]:
# for range of elements     suse the syntax"ARANGE"
arr_arr=np.arange(10)
print(arr_arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
# Diagonal elements      use the syntax "EYE"

import numpy as np 
dig = np.eye (3)
print(dig)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
# soace liberaly in a specified internal 
import numpy as np 
arr_lin=np.linspace(0,20,num=5)
print(arr_lin)

[ 0.  5. 10. 15. 20.]
