In [1]:
# Rand() to generate a random no between 0 & 1 eg.
import numpy as np
a=np.random.rand(4)
print(a)

[0.22615792 0.5056342  0.16508607 0.87415476]


In [3]:
# for 2D array 
b=np.random.rand(2,3)
print(b)

[[0.56435631 0.21455994 0.13722802]
 [0.85533153 0.46623039 0.94609678]]


In [6]:
 # RANDN()  to generate a random no. which is close to 0 & it can be +ve 7 -ve
c= np.random.randn(3)
print(c)

[ 0.98608528 -1.11673887  1.6641005 ]


In [7]:
# Ranf()
d=np.random.ranf(2)
print(d)

[0.74999077 0.51207672]


In [11]:
# randit    to generate a random number between 2 number
e=np.random.randint(2,20,5)
print(e)

[ 5 12  9  6 10]
