          # Shapes and reshaping array 
 to defien which type of dimesions is the list  & retrieve the size

In [3]:
import numpy as np 
var=np.array([[2,2],[3,3]])
print(var)
print()   # to add a  empty line
print(var.shape)  # to determine the row and columns 

[[2 2]
 [3 3]]

(2, 2)


In [9]:
 # to  multi dimensions array use the function ndmin=(how many dimensio you want 
 a=np.array([1,2],ndmin=4)
print(a)
print(a.ndim)
print()
print(a.shape)

[[[[1 2]]]]
4

(1, 1, 1, 2)


                Reshaping (from multi dimension to 1 d)
            

In [36]:
import numpy as np 
vst=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(vst.ndim)
x= vst.reshape(2,3,2)
print(x)
print(x.ndim)

1
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
